# Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
# Production pattern: Kubernetes workload using SPIRE CSI driver

apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-workload
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sovereign-workload
  namespace: default
  labels:
    app: test-sovereign-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-sovereign-workload
  template:
    metadata:
      labels:
        app: test-sovereign-workload
    spec:
      serviceAccountName: test-workload
      containers:
      - name: workload
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Unified-Identity - Phase 1: Testing Sovereign SVID in Kubernetes"
          echo "SPIRE Workload API socket location: /run/spire/sockets/workload_api.sock"
          echo ""
          # Wait for socket (CSI driver will mount it)
          for i in $(seq 1 60); do
            if [ -S /run/spire/sockets/workload_api.sock ]; then
              echo "✓ SPIRE Workload API socket found!"
              break
            fi
            echo "Waiting for SPIRE Workload API socket... ($i/60)"
            sleep 1
          done
          
          if [ ! -S /run/spire/sockets/workload_api.sock ]; then
            echo "✗ SPIRE Workload API socket not found"
            ls -la /run/spire/sockets/ || true
            exit 1
          fi
          
          echo ""
          echo "Socket details:"
          ls -la /run/spire/sockets/workload_api.sock
          echo ""
          echo "✓ Socket accessible - ready for SVID retrieval"
          echo ""
          echo "Note: To retrieve SVID, use a workload API client or spire-agent CLI"
          echo "      For Phase 1 testing with SovereignAttestation, use generate-sovereign-svid"
          echo "      script from the host instead."
          echo ""
          sleep 3600
        volumeMounts:
        - name: spire-workload-api
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: spire-workload-api
        # Unified-Identity - Phase 1: Production pattern using SPIRE CSI driver
        csi:
          driver: csi.spiffe.io
          volumeAttributes:
            workloadAPI: "/run/spire/sockets/workload_api.sock"
