# Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
# Simple test workload using hostPath mount (non-CSI driver option)
# This is a simpler alternative while CSI driver image issue is resolved

apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-workload
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sovereign-workload
  namespace: default
  labels:
    app: test-sovereign-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-sovereign-workload
  template:
    metadata:
      labels:
        app: test-sovereign-workload
    spec:
      serviceAccountName: test-workload
      containers:
      - name: workload
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Unified-Identity - Phase 1: Testing Sovereign SVID in Kubernetes"
          echo "SPIRE Agent socket location: /run/spire/sockets/api.sock"
          echo ""
          # Wait for socket
          for i in $(seq 1 30); do
            if [ -S /run/spire/sockets/api.sock ]; then
              echo "✓ SPIRE Agent socket found!"
              break
            fi
            echo "Waiting for SPIRE Agent socket... ($i/30)"
            sleep 1
          done
          
          if [ ! -S /run/spire/sockets/api.sock ]; then
            echo "✗ SPIRE Agent socket not found"
            ls -la /run/spire/sockets/ || true
            exit 1
          fi
          
          echo ""
          echo "Socket details:"
          ls -la /run/spire/sockets/api.sock
          echo ""
          echo "✓ Socket accessible - ready for SVID retrieval"
          echo ""
          echo "To dump SVID from this pod, use:"
          echo "  kubectl exec <pod-name> -- spire-agent api fetch -socketPath /run/spire/sockets/api.sock -write /tmp"
          echo "  kubectl cp <pod-name>:/tmp/svid.0.pem /tmp/svid.crt"
          echo ""
          sleep 3600
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: spire-agent-socket
        # Unified-Identity - Phase 1: Simple hostPath mount (non-CSI driver option)
        # This is a simpler alternative while CSI driver image issue is resolved
        hostPath:
          path: /tmp/spire-agent/public
          type: Directory
