apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-ca
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: demo-ca
  namespace: default
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-ca
  namespace: default
spec:
  isCA: true
  commonName: demo-ca
  secretName: ca-key-pair 
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer