#!/usr/bin/env python3
"""
Unified-Identity - Phase 3: Hardware Integration & Delegated Certification

CLI wrapper for TPM Plugin
This script provides a command-line interface for the TPM plugin,
allowing it to be called from SPIRE Agent (Go code).
"""

import argparse
import json
import logging
import sys
from pathlib import Path

from tpm_plugin import TPMPlugin, is_unified_identity_enabled
from delegated_certification import DelegatedCertificationClient

# Unified-Identity - Phase 3: Hardware Integration & Delegated Certification
# Configure logging to stderr so JSON output on stdout is clean
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    stream=sys.stderr  # Send logs to stderr, not stdout
)
logger = logging.getLogger(__name__)


# Unified-Identity - Phase 3: Hardware Integration & Delegated Certification
def cmd_generate_app_key(args):
    """Generate App Key command"""
    if not is_unified_identity_enabled():
        logger.error("Unified-Identity - Phase 3: Feature flag disabled")
        sys.exit(1)
    
    plugin = TPMPlugin(work_dir=args.work_dir)
    success, app_key_public, app_key_ctx = plugin.generate_app_key(force=args.force)
    
    if not success:
        logger.error("Unified-Identity - Phase 3: Failed to generate App Key")
        sys.exit(1)
    
    # Output JSON
    result = {
        "app_key_public": app_key_public,
        "app_key_context": app_key_ctx,
        "status": "success"
    }
    print(json.dumps(result))
    sys.exit(0)


# Unified-Identity - Phase 3: Hardware Integration & Delegated Certification
# Quote generation removed - quotes are generated by rust-keylime agent and requested by Keylime verifier
def cmd_request_certificate(args):
    """Request App Key certificate command"""
    if not is_unified_identity_enabled():
        logger.error("Unified-Identity - Phase 3: Feature flag disabled")
        sys.exit(1)
    
    if not args.app_key_public or not args.app_key_context:
        logger.error("Unified-Identity - Phase 3: App key public and context are required")
        sys.exit(1)
    
    # Unified-Identity - Phase 3: Support both --endpoint and --socket-path (for backward compatibility)
    endpoint = args.endpoint
    if endpoint is None and args.socket_path:
        # Legacy: convert socket path to endpoint format
        endpoint = f"unix://{args.socket_path}"
    
    client = DelegatedCertificationClient(endpoint=endpoint)
    success, cert_b64, agent_uuid, error = client.request_certificate(
        app_key_public=args.app_key_public,
        app_key_context_path=args.app_key_context
    )
    
    if not success:
        logger.error("Unified-Identity - Phase 3: Failed to request certificate: %s", error)
        sys.exit(1)
    
    # Output JSON with base64 certificate and agent UUID (if provided)
    result = {
        "app_key_certificate": cert_b64,
        "agent_uuid": agent_uuid
    }
    print(json.dumps(result))
    sys.exit(0)


# Unified-Identity - Phase 3: Hardware Integration & Delegated Certification
def main():
    """Main CLI entry point"""
    parser = argparse.ArgumentParser(
        description="Unified-Identity - Phase 3: TPM Plugin CLI"
    )
    subparsers = parser.add_subparsers(dest="command", help="Command to execute")
    
    # Generate App Key command
    parser_generate = subparsers.add_parser("generate-app-key", help="Generate App Key")
    parser_generate.add_argument("--work-dir", type=str, help="Working directory")
    parser_generate.add_argument("--force", action="store_true", help="Force regeneration")
    parser_generate.set_defaults(func=cmd_generate_app_key)
    
    # Unified-Identity - Phase 3: Quote generation removed from TPM plugin
    # Quotes are generated by rust-keylime agent and requested by Keylime verifier
    
    # Request Certificate command
    parser_cert = subparsers.add_parser("request-certificate", help="Request App Key certificate")
    parser_cert.add_argument("--app-key-public", type=str, required=True, help="App Key public key (PEM)")
    parser_cert.add_argument("--app-key-context", type=str, required=True, help="App Key context path")
    parser_cert.add_argument("--endpoint", type=str, 
                            default=None,
                            help="rust-keylime Agent endpoint (UDS socket only). Defaults to unix:///tmp/keylime-agent.sock. HTTP over localhost is not supported for security reasons.")
    parser_cert.add_argument("--socket-path", type=str, 
                            default=None,
                            help="[Deprecated] Use --endpoint instead. Keylime Agent socket path")
    parser_cert.set_defaults(func=cmd_request_certificate)
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        sys.exit(1)
    
    args.func(args)


if __name__ == "__main__":
    main()

