// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: spire/api/types/sovereignattestation.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
// A hardware-rooted PoR package produced by the Agent.
type SovereignAttestation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64-encoded TPM Quote (portable string). Validation: non-empty, base64, size <= 64kB
	TpmSignedAttestation string `protobuf:"bytes,1,opt,name=tpm_signed_attestation,json=tpmSignedAttestation,proto3" json:"tpm_signed_attestation,omitempty"`
	// The App Key public key (PEM or base64-encoded). Preferred format: PEM.
	// Validation: when present must parse; server-side validation enforced.
	AppKeyPublic string `protobuf:"bytes,2,opt,name=app_key_public,json=appKeyPublic,proto3" json:"app_key_public,omitempty"`
	// Optional base64-encoded DER or PEM certificate proving the App Key was issued/signed by the host AK.
	// **CLARIFICATION:** This field MUST be Base64-encoded when transmitted over a JSON/REST boundary (e.g., to Keylime).
	// Validation: when present must parse to X.509 cert; chain verification will be performed by Keylime.
	AppKeyCertificate []byte `protobuf:"bytes,3,opt,name=app_key_certificate,json=appKeyCertificate,proto3" json:"app_key_certificate,omitempty"`
	// The SPIRE Server nonce used for freshness verification.
	ChallengeNonce string `protobuf:"bytes,4,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"`
	// Optional workload code hash used as an additional selector/assertion.
	WorkloadCodeHash string `protobuf:"bytes,5,opt,name=workload_code_hash,json=workloadCodeHash,proto3" json:"workload_code_hash,omitempty"`
	// Unified-Identity - Phase 3: rust-keylime agent UUID for delegated certification correlation.
	KeylimeAgentUuid string `protobuf:"bytes,6,opt,name=keylime_agent_uuid,json=keylimeAgentUuid,proto3" json:"keylime_agent_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SovereignAttestation) Reset() {
	*x = SovereignAttestation{}
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SovereignAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SovereignAttestation) ProtoMessage() {}

func (x *SovereignAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SovereignAttestation.ProtoReflect.Descriptor instead.
func (*SovereignAttestation) Descriptor() ([]byte, []int) {
	return file_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{0}
}

func (x *SovereignAttestation) GetTpmSignedAttestation() string {
	if x != nil {
		return x.TpmSignedAttestation
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyPublic() string {
	if x != nil {
		return x.AppKeyPublic
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyCertificate() []byte {
	if x != nil {
		return x.AppKeyCertificate
	}
	return nil
}

func (x *SovereignAttestation) GetChallengeNonce() string {
	if x != nil {
		return x.ChallengeNonce
	}
	return ""
}

func (x *SovereignAttestation) GetWorkloadCodeHash() string {
	if x != nil {
		return x.WorkloadCodeHash
	}
	return ""
}

func (x *SovereignAttestation) GetKeylimeAgentUuid() string {
	if x != nil {
		return x.KeylimeAgentUuid
	}
	return ""
}

// Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
// AttestedClaims contains verified facts from Keylime about the host.
type AttestedClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geolocation   *Geolocation           `protobuf:"bytes,1,opt,name=geolocation,proto3" json:"geolocation,omitempty"` // Geolocation object with type, sensor_id, and optional value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedClaims) Reset() {
	*x = AttestedClaims{}
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedClaims) ProtoMessage() {}

func (x *AttestedClaims) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedClaims.ProtoReflect.Descriptor instead.
func (*AttestedClaims) Descriptor() ([]byte, []int) {
	return file_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{1}
}

func (x *AttestedClaims) GetGeolocation() *Geolocation {
	if x != nil {
		return x.Geolocation
	}
	return nil
}

// Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
// Geolocation represents geolocation sensor metadata
type Geolocation struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Type         string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                     // "mobile" or "gnss"
	SensorId     string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`             // Sensor identifier (e.g., USB ID "12d1:1433" for mobile)
	Value        string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                   // Optional for mobile, mandatory for gnss (e.g., GNSS coordinates)
	SensorImei   string                 `protobuf:"bytes,4,opt,name=sensor_imei,json=sensorImei,proto3" json:"sensor_imei,omitempty"`       // IMEI for mobile devices
	SensorImsi   string                 `protobuf:"bytes,5,opt,name=sensor_imsi,json=sensorImsi,proto3" json:"sensor_imsi,omitempty"`       // IMSI for mobile devices
	SensorMsisdn string                 `protobuf:"bytes,6,opt,name=sensor_msisdn,json=sensorMsisdn,proto3" json:"sensor_msisdn,omitempty"` // MSISDN for mobile devices
	// GNSS-specific fields
	SensorSerialNumber string  `protobuf:"bytes,7,opt,name=sensor_serial_number,json=sensorSerialNumber,proto3" json:"sensor_serial_number,omitempty"`
	Latitude           float64 `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude          float64 `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy           float64 `protobuf:"fixed64,10,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	SensorSignature    string  `protobuf:"bytes,11,opt,name=sensor_signature,json=sensorSignature,proto3" json:"sensor_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Geolocation) Reset() {
	*x = Geolocation{}
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geolocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geolocation) ProtoMessage() {}

func (x *Geolocation) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geolocation.ProtoReflect.Descriptor instead.
func (*Geolocation) Descriptor() ([]byte, []int) {
	return file_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{2}
}

func (x *Geolocation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Geolocation) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Geolocation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Geolocation) GetSensorImei() string {
	if x != nil {
		return x.SensorImei
	}
	return ""
}

func (x *Geolocation) GetSensorImsi() string {
	if x != nil {
		return x.SensorImsi
	}
	return ""
}

func (x *Geolocation) GetSensorMsisdn() string {
	if x != nil {
		return x.SensorMsisdn
	}
	return ""
}

func (x *Geolocation) GetSensorSerialNumber() string {
	if x != nil {
		return x.SensorSerialNumber
	}
	return ""
}

func (x *Geolocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Geolocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Geolocation) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Geolocation) GetSensorSignature() string {
	if x != nil {
		return x.SensorSignature
	}
	return ""
}

var File_spire_api_types_sovereignattestation_proto protoreflect.FileDescriptor

const file_spire_api_types_sovereignattestation_proto_rawDesc = "" +
	"\n" +
	"*spire/api/types/sovereignattestation.proto\x12\x0fspire.api.types\"\xa7\x02\n" +
	"\x14SovereignAttestation\x124\n" +
	"\x16tpm_signed_attestation\x18\x01 \x01(\tR\x14tpmSignedAttestation\x12$\n" +
	"\x0eapp_key_public\x18\x02 \x01(\tR\fappKeyPublic\x12.\n" +
	"\x13app_key_certificate\x18\x03 \x01(\fR\x11appKeyCertificate\x12'\n" +
	"\x0fchallenge_nonce\x18\x04 \x01(\tR\x0echallengeNonce\x12,\n" +
	"\x12workload_code_hash\x18\x05 \x01(\tR\x10workloadCodeHash\x12,\n" +
	"\x12keylime_agent_uuid\x18\x06 \x01(\tR\x10keylimeAgentUuid\"P\n" +
	"\x0eAttestedClaims\x12>\n" +
	"\vgeolocation\x18\x01 \x01(\v2\x1c.spire.api.types.GeolocationR\vgeolocation\"\xee\x02\n" +
	"\vGeolocation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1f\n" +
	"\vsensor_imei\x18\x04 \x01(\tR\n" +
	"sensorImei\x12\x1f\n" +
	"\vsensor_imsi\x18\x05 \x01(\tR\n" +
	"sensorImsi\x12#\n" +
	"\rsensor_msisdn\x18\x06 \x01(\tR\fsensorMsisdn\x120\n" +
	"\x14sensor_serial_number\x18\a \x01(\tR\x12sensorSerialNumber\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\n" +
	" \x01(\x01R\baccuracy\x12)\n" +
	"\x10sensor_signature\x18\v \x01(\tR\x0fsensorSignatureB7Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3"

var (
	file_spire_api_types_sovereignattestation_proto_rawDescOnce sync.Once
	file_spire_api_types_sovereignattestation_proto_rawDescData []byte
)

func file_spire_api_types_sovereignattestation_proto_rawDescGZIP() []byte {
	file_spire_api_types_sovereignattestation_proto_rawDescOnce.Do(func() {
		file_spire_api_types_sovereignattestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_api_types_sovereignattestation_proto_rawDesc), len(file_spire_api_types_sovereignattestation_proto_rawDesc)))
	})
	return file_spire_api_types_sovereignattestation_proto_rawDescData
}

var file_spire_api_types_sovereignattestation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spire_api_types_sovereignattestation_proto_goTypes = []any{
	(*SovereignAttestation)(nil), // 0: spire.api.types.SovereignAttestation
	(*AttestedClaims)(nil),       // 1: spire.api.types.AttestedClaims
	(*Geolocation)(nil),          // 2: spire.api.types.Geolocation
}
var file_spire_api_types_sovereignattestation_proto_depIdxs = []int32{
	2, // 0: spire.api.types.AttestedClaims.geolocation:type_name -> spire.api.types.Geolocation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_api_types_sovereignattestation_proto_init() }
func file_spire_api_types_sovereignattestation_proto_init() {
	if File_spire_api_types_sovereignattestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_api_types_sovereignattestation_proto_rawDesc), len(file_spire_api_types_sovereignattestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spire_api_types_sovereignattestation_proto_goTypes,
		DependencyIndexes: file_spire_api_types_sovereignattestation_proto_depIdxs,
		MessageInfos:      file_spire_api_types_sovereignattestation_proto_msgTypes,
	}.Build()
	File_spire_api_types_sovereignattestation_proto = out.File
	file_spire_api_types_sovereignattestation_proto_goTypes = nil
	file_spire_api_types_sovereignattestation_proto_depIdxs = nil
}
