#!/bin/bash

set -ex

# start the server and agent
docker compose up -d --build

# wait for the server to be ready
docker-wait-for-healthy spire-server 60 1

# wait for the agent to be ready
docker-wait-for-healthy spire-agent 60 1

# run the client
docker compose run --rm sovereign-attestation
