FROM golang:1.20 as builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG BUILD_TAGS
RUN go build -tags "unified_identity" -o /build/spire-server ./cmd/spire-server
RUN go build -tags "unified_identity" -o /build/spire-agent ./cmd/spire-agent

FROM debian:11

COPY --from=builder /build/spire-server /usr/bin/spire-server
COPY --from=builder /build/spire-agent /usr/bin/spire-agent

ENTRYPOINT ["/usr/bin/spire-server"]
