// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: spire-api-sdk/proto/spire/api/types/sovereignattestation.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestedClaims_HostIntegrity int32

const (
	AttestedClaims_HOST_INTEGRITY_UNSPECIFIED AttestedClaims_HostIntegrity = 0
	AttestedClaims_PASSED_ALL_CHECKS          AttestedClaims_HostIntegrity = 1
	AttestedClaims_FAILED                     AttestedClaims_HostIntegrity = 2
	AttestedClaims_PARTIAL                    AttestedClaims_HostIntegrity = 3
)

// Enum value maps for AttestedClaims_HostIntegrity.
var (
	AttestedClaims_HostIntegrity_name = map[int32]string{
		0: "HOST_INTEGRITY_UNSPECIFIED",
		1: "PASSED_ALL_CHECKS",
		2: "FAILED",
		3: "PARTIAL",
	}
	AttestedClaims_HostIntegrity_value = map[string]int32{
		"HOST_INTEGRITY_UNSPECIFIED": 0,
		"PASSED_ALL_CHECKS":          1,
		"FAILED":                     2,
		"PARTIAL":                    3,
	}
)

func (x AttestedClaims_HostIntegrity) Enum() *AttestedClaims_HostIntegrity {
	p := new(AttestedClaims_HostIntegrity)
	*p = x
	return p
}

func (x AttestedClaims_HostIntegrity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttestedClaims_HostIntegrity) Descriptor() protoreflect.EnumDescriptor {
	return file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_enumTypes[0].Descriptor()
}

func (AttestedClaims_HostIntegrity) Type() protoreflect.EnumType {
	return &file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_enumTypes[0]
}

func (x AttestedClaims_HostIntegrity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttestedClaims_HostIntegrity.Descriptor instead.
func (AttestedClaims_HostIntegrity) EnumDescriptor() ([]byte, []int) {
	return file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{1, 0}
}

// Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
// A hardware-rooted PoR package produced by the Agent.
type SovereignAttestation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64-encoded TPM Quote (portable string). Validation: non-empty, base64, size <= 64kB
	TpmSignedAttestation string `protobuf:"bytes,1,opt,name=tpm_signed_attestation,json=tpmSignedAttestation,proto3" json:"tpm_signed_attestation,omitempty"`
	// The App Key public key (PEM or base64-encoded). Preferred format: PEM.
	// Validation: when present must parse; server-side validation enforced.
	AppKeyPublic string `protobuf:"bytes,2,opt,name=app_key_public,json=appKeyPublic,proto3" json:"app_key_public,omitempty"`
	// Optional base64-encoded DER or PEM certificate proving the App Key was issued/signed by the host AK.
	// **CLARIFICATION:** This field MUST be Base64-encoded when transmitted over a JSON/REST boundary (e.g., to Keylime).
	// Validation: when present must parse to X.509 cert; chain verification will be performed by Keylime.
	AppKeyCertificate []byte `protobuf:"bytes,3,opt,name=app_key_certificate,json=appKeyCertificate,proto3" json:"app_key_certificate,omitempty"`
	// The SPIRE Server nonce used for freshness verification.
	ChallengeNonce string `protobuf:"bytes,4,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"`
	// Optional workload code hash used as an additional selector/assertion.
	WorkloadCodeHash string `protobuf:"bytes,5,opt,name=workload_code_hash,json=workloadCodeHash,proto3" json:"workload_code_hash,omitempty"`
	// Unified-Identity - Phase 3: rust-keylime agent UUID for delegated certification correlation.
	KeylimeAgentUuid string `protobuf:"bytes,6,opt,name=keylime_agent_uuid,json=keylimeAgentUuid,proto3" json:"keylime_agent_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SovereignAttestation) Reset() {
	*x = SovereignAttestation{}
	mi := &file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SovereignAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SovereignAttestation) ProtoMessage() {}

func (x *SovereignAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SovereignAttestation.ProtoReflect.Descriptor instead.
func (*SovereignAttestation) Descriptor() ([]byte, []int) {
	return file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{0}
}

func (x *SovereignAttestation) GetTpmSignedAttestation() string {
	if x != nil {
		return x.TpmSignedAttestation
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyPublic() string {
	if x != nil {
		return x.AppKeyPublic
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyCertificate() []byte {
	if x != nil {
		return x.AppKeyCertificate
	}
	return nil
}

func (x *SovereignAttestation) GetChallengeNonce() string {
	if x != nil {
		return x.ChallengeNonce
	}
	return ""
}

func (x *SovereignAttestation) GetWorkloadCodeHash() string {
	if x != nil {
		return x.WorkloadCodeHash
	}
	return ""
}

func (x *SovereignAttestation) GetKeylimeAgentUuid() string {
	if x != nil {
		return x.KeylimeAgentUuid
	}
	return ""
}

// Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
// AttestedClaims contains verified facts from Keylime about the host.
type AttestedClaims struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	Geolocation         string                       `protobuf:"bytes,1,opt,name=geolocation,proto3" json:"geolocation,omitempty"` // structured preferred; free-form fallback allowed
	HostIntegrityStatus AttestedClaims_HostIntegrity `protobuf:"varint,2,opt,name=host_integrity_status,json=hostIntegrityStatus,proto3,enum=spire.api.types.AttestedClaims_HostIntegrity" json:"host_integrity_status,omitempty"`
	GpuMetricsHealth    *AttestedClaims_GpuMetrics   `protobuf:"bytes,3,opt,name=gpu_metrics_health,json=gpuMetricsHealth,proto3" json:"gpu_metrics_health,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttestedClaims) Reset() {
	*x = AttestedClaims{}
	mi := &file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedClaims) ProtoMessage() {}

func (x *AttestedClaims) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedClaims.ProtoReflect.Descriptor instead.
func (*AttestedClaims) Descriptor() ([]byte, []int) {
	return file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{1}
}

func (x *AttestedClaims) GetGeolocation() string {
	if x != nil {
		return x.Geolocation
	}
	return ""
}

func (x *AttestedClaims) GetHostIntegrityStatus() AttestedClaims_HostIntegrity {
	if x != nil {
		return x.HostIntegrityStatus
	}
	return AttestedClaims_HOST_INTEGRITY_UNSPECIFIED
}

func (x *AttestedClaims) GetGpuMetricsHealth() *AttestedClaims_GpuMetrics {
	if x != nil {
		return x.GpuMetricsHealth
	}
	return nil
}

type AttestedClaims_GpuMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                         // 'healthy', 'degraded', 'failed'
	UtilizationPct float64                `protobuf:"fixed64,2,opt,name=utilization_pct,json=utilizationPct,proto3" json:"utilization_pct,omitempty"` // 0..100
	MemoryMb       int64                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttestedClaims_GpuMetrics) Reset() {
	*x = AttestedClaims_GpuMetrics{}
	mi := &file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedClaims_GpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedClaims_GpuMetrics) ProtoMessage() {}

func (x *AttestedClaims_GpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedClaims_GpuMetrics.ProtoReflect.Descriptor instead.
func (*AttestedClaims_GpuMetrics) Descriptor() ([]byte, []int) {
	return file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AttestedClaims_GpuMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AttestedClaims_GpuMetrics) GetUtilizationPct() float64 {
	if x != nil {
		return x.UtilizationPct
	}
	return 0
}

func (x *AttestedClaims_GpuMetrics) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

var File_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto protoreflect.FileDescriptor

const file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDesc = "" +
	"\n" +
	">spire-api-sdk/proto/spire/api/types/sovereignattestation.proto\x12\x0fspire.api.types\"\xa7\x02\n" +
	"\x14SovereignAttestation\x124\n" +
	"\x16tpm_signed_attestation\x18\x01 \x01(\tR\x14tpmSignedAttestation\x12$\n" +
	"\x0eapp_key_public\x18\x02 \x01(\tR\fappKeyPublic\x12.\n" +
	"\x13app_key_certificate\x18\x03 \x01(\fR\x11appKeyCertificate\x12'\n" +
	"\x0fchallenge_nonce\x18\x04 \x01(\tR\x0echallengeNonce\x12,\n" +
	"\x12workload_code_hash\x18\x05 \x01(\tR\x10workloadCodeHash\x12,\n" +
	"\x12keylime_agent_uuid\x18\x06 \x01(\tR\x10keylimeAgentUuid\"\xbc\x03\n" +
	"\x0eAttestedClaims\x12 \n" +
	"\vgeolocation\x18\x01 \x01(\tR\vgeolocation\x12a\n" +
	"\x15host_integrity_status\x18\x02 \x01(\x0e2-.spire.api.types.AttestedClaims.HostIntegrityR\x13hostIntegrityStatus\x12X\n" +
	"\x12gpu_metrics_health\x18\x03 \x01(\v2*.spire.api.types.AttestedClaims.GpuMetricsR\x10gpuMetricsHealth\x1aj\n" +
	"\n" +
	"GpuMetrics\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0futilization_pct\x18\x02 \x01(\x01R\x0eutilizationPct\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x03R\bmemoryMb\"_\n" +
	"\rHostIntegrity\x12\x1e\n" +
	"\x1aHOST_INTEGRITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PASSED_ALL_CHECKS\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\v\n" +
	"\aPARTIAL\x10\x03B7Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3"

var (
	file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescOnce sync.Once
	file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescData []byte
)

func file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescGZIP() []byte {
	file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescOnce.Do(func() {
		file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDesc), len(file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDesc)))
	})
	return file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDescData
}

var file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_goTypes = []any{
	(AttestedClaims_HostIntegrity)(0), // 0: spire.api.types.AttestedClaims.HostIntegrity
	(*SovereignAttestation)(nil),      // 1: spire.api.types.SovereignAttestation
	(*AttestedClaims)(nil),            // 2: spire.api.types.AttestedClaims
	(*AttestedClaims_GpuMetrics)(nil), // 3: spire.api.types.AttestedClaims.GpuMetrics
}
var file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_depIdxs = []int32{
	0, // 0: spire.api.types.AttestedClaims.host_integrity_status:type_name -> spire.api.types.AttestedClaims.HostIntegrity
	3, // 1: spire.api.types.AttestedClaims.gpu_metrics_health:type_name -> spire.api.types.AttestedClaims.GpuMetrics
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_init() }
func file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_init() {
	if File_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDesc), len(file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_goTypes,
		DependencyIndexes: file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_depIdxs,
		EnumInfos:         file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_enumTypes,
		MessageInfos:      file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_msgTypes,
	}.Build()
	File_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto = out.File
	file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_goTypes = nil
	file_spire_api_sdk_proto_spire_api_types_sovereignattestation_proto_depIdxs = nil
}
