// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: proto/spire/api/types/sovereign.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestedClaims_HostIntegrity int32

const (
	AttestedClaims_HOST_INTEGRITY_UNSPECIFIED AttestedClaims_HostIntegrity = 0
	AttestedClaims_PASSED_ALL_CHECKS          AttestedClaims_HostIntegrity = 1
	AttestedClaims_FAILED                     AttestedClaims_HostIntegrity = 2
	AttestedClaims_PARTIAL                    AttestedClaims_HostIntegrity = 3
)

// Enum value maps for AttestedClaims_HostIntegrity.
var (
	AttestedClaims_HostIntegrity_name = map[int32]string{
		0: "HOST_INTEGRITY_UNSPECIFIED",
		1: "PASSED_ALL_CHECKS",
		2: "FAILED",
		3: "PARTIAL",
	}
	AttestedClaims_HostIntegrity_value = map[string]int32{
		"HOST_INTEGRITY_UNSPECIFIED": 0,
		"PASSED_ALL_CHECKS":          1,
		"FAILED":                     2,
		"PARTIAL":                    3,
	}
)

func (x AttestedClaims_HostIntegrity) Enum() *AttestedClaims_HostIntegrity {
	p := new(AttestedClaims_HostIntegrity)
	*p = x
	return p
}

func (x AttestedClaims_HostIntegrity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttestedClaims_HostIntegrity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_spire_api_types_sovereign_proto_enumTypes[0].Descriptor()
}

func (AttestedClaims_HostIntegrity) Type() protoreflect.EnumType {
	return &file_proto_spire_api_types_sovereign_proto_enumTypes[0]
}

func (x AttestedClaims_HostIntegrity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttestedClaims_HostIntegrity.Descriptor instead.
func (AttestedClaims_HostIntegrity) EnumDescriptor() ([]byte, []int) {
	return file_proto_spire_api_types_sovereign_proto_rawDescGZIP(), []int{1, 0}
}

// A hardware-rooted PoR package produced by the Agent.
type SovereignAttestation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Base64-encoded TPM Quote (portable string). Validation: non-empty, base64,
	// size <= 64kB
	TpmSignedAttestation string `protobuf:"bytes,1,opt,name=tpm_signed_attestation,json=tpmSignedAttestation,proto3" json:"tpm_signed_attestation,omitempty"`
	// The App Key public key (PEM or base64-encoded). Preferred format: PEM.
	// Validation: when present must parse; server-side validation enforced.
	AppKeyPublic string `protobuf:"bytes,2,opt,name=app_key_public,json=appKeyPublic,proto3" json:"app_key_public,omitempty"`
	// Optional base64-encoded DER or PEM certificate proving the App Key was
	// issued/signed by the host AK.
	// **CLARIFICATION:** This field MUST be Base64-encoded when transmitted over
	// a JSON/REST boundary (e.g., to Keylime).
	// Validation: when present must parse to X.509 cert; chain verification will
	// be performed by Keylime.
	AppKeyCertificate []byte `protobuf:"bytes,3,opt,name=app_key_certificate,json=appKeyCertificate,proto3" json:"app_key_certificate,omitempty"`
	// The SPIRE Server nonce used for freshness verification.
	ChallengeNonce string `protobuf:"bytes,4,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"`
	// Optional workload code hash used as an additional selector/assertion.
	WorkloadCodeHash string `protobuf:"bytes,5,opt,name=workload_code_hash,json=workloadCodeHash,proto3" json:"workload_code_hash,omitempty"`
}

func (x *SovereignAttestation) Reset() {
	*x = SovereignAttestation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spire_api_types_sovereign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SovereignAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SovereignAttestation) ProtoMessage() {}

func (x *SovereignAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spire_api_types_sovereign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SovereignAttestation.ProtoReflect.Descriptor instead.
func (*SovereignAttestation) Descriptor() ([]byte, []int) {
	return file_proto_spire_api_types_sovereign_proto_rawDescGZIP(), []int{0}
}

func (x *SovereignAttestation) GetTpmSignedAttestation() string {
	if x != nil {
		return x.TpmSignedAttestation
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyPublic() string {
	if x != nil {
		return x.AppKeyPublic
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyCertificate() []byte {
	if x != nil {
		return x.AppKeyCertificate
	}
	return nil
}

func (x *SovereignAttestation) GetChallengeNonce() string {
	if x != nil {
		return x.ChallengeNonce
	}
	return ""
}

func (x *SovereignAttestation) GetWorkloadCodeHash() string {
	if x != nil {
		return x.WorkloadCodeHash
	}
	return ""
}

type AttestedClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Geolocation         string                       `protobuf:"bytes,1,opt,name=geolocation,proto3" json:"geolocation,omitempty"` // structured preferred; free-form fallback allowed
	HostIntegrityStatus AttestedClaims_HostIntegrity `protobuf:"varint,2,opt,name=host_integrity_status,json=hostIntegrityStatus,proto3,enum=spire.api.types.AttestedClaims_HostIntegrity" json:"host_integrity_status,omitempty"`
	GpuMetricsHealth    *AttestedClaims_GpuMetrics   `protobuf:"bytes,3,opt,name=gpu_metrics_health,json=gpuMetricsHealth,proto3" json:"gpu_metrics_health,omitempty"`
}

func (x *AttestedClaims) Reset() {
	*x = AttestedClaims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spire_api_types_sovereign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttestedClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedClaims) ProtoMessage() {}

func (x *AttestedClaims) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spire_api_types_sovereign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedClaims.ProtoReflect.Descriptor instead.
func (*AttestedClaims) Descriptor() ([]byte, []int) {
	return file_proto_spire_api_types_sovereign_proto_rawDescGZIP(), []int{1}
}

func (x *AttestedClaims) GetGeolocation() string {
	if x != nil {
		return x.Geolocation
	}
	return ""
}

func (x *AttestedClaims) GetHostIntegrityStatus() AttestedClaims_HostIntegrity {
	if x != nil {
		return x.HostIntegrityStatus
	}
	return AttestedClaims_HOST_INTEGRITY_UNSPECIFIED
}

func (x *AttestedClaims) GetGpuMetricsHealth() *AttestedClaims_GpuMetrics {
	if x != nil {
		return x.GpuMetricsHealth
	}
	return nil
}

type AttestedClaims_GpuMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         string  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                         // 'healthy', 'degraded', 'failed'
	UtilizationPct float64 `protobuf:"fixed64,2,opt,name=utilization_pct,json=utilizationPct,proto3" json:"utilization_pct,omitempty"` // 0..100
	MemoryMb       int64   `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
}

func (x *AttestedClaims_GpuMetrics) Reset() {
	*x = AttestedClaims_GpuMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spire_api_types_sovereign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttestedClaims_GpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedClaims_GpuMetrics) ProtoMessage() {}

func (x *AttestedClaims_GpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spire_api_types_sovereign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedClaims_GpuMetrics.ProtoReflect.Descriptor instead.
func (*AttestedClaims_GpuMetrics) Descriptor() ([]byte, []int) {
	return file_proto_spire_api_types_sovereign_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AttestedClaims_GpuMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AttestedClaims_GpuMetrics) GetUtilizationPct() float64 {
	if x != nil {
		return x.UtilizationPct
	}
	return 0
}

func (x *AttestedClaims_GpuMetrics) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

var File_proto_spire_api_types_sovereign_proto protoreflect.FileDescriptor

var file_proto_spire_api_types_sovereign_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x73, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x69, 0x67,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x14, 0x53, 0x6f, 0x76,
	0x65, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x34, 0x0a, 0x16, 0x74, 0x70, 0x6d, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x74, 0x70, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x5f, 0x6b,
	0x65, 0x79, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x2e, 0x0a,
	0x13, 0x61, 0x70, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x61, 0x70, 0x70, 0x4b,
	0x65, 0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x22, 0xbc, 0x03, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x65, 0x6f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x65,
	0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x61, 0x0a, 0x15, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x52, 0x13, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x58, 0x0a, 0x12,
	0x67, 0x70, 0x75, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2e, 0x47, 0x70, 0x75, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x52, 0x10, 0x67, 0x70, 0x75, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x1a, 0x6a, 0x0a, 0x0a, 0x47, 0x70, 0x75, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x75, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f,
	0x6d, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x4d, 0x62, 0x22, 0x5f, 0x0a, 0x0d, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x1a, 0x48, 0x4f, 0x53, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x45,
	0x47, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x41, 0x53, 0x53, 0x45, 0x44, 0x5f, 0x41, 0x4c,
	0x4c, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41,
	0x4c, 0x10, 0x03, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2d, 0x61,
	0x70, 0x69, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x69,
	0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spire_api_types_sovereign_proto_rawDescOnce sync.Once
	file_proto_spire_api_types_sovereign_proto_rawDescData = file_proto_spire_api_types_sovereign_proto_rawDesc
)

func file_proto_spire_api_types_sovereign_proto_rawDescGZIP() []byte {
	file_proto_spire_api_types_sovereign_proto_rawDescOnce.Do(func() {
		file_proto_spire_api_types_sovereign_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spire_api_types_sovereign_proto_rawDescData)
	})
	return file_proto_spire_api_types_sovereign_proto_rawDescData
}

var file_proto_spire_api_types_sovereign_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_spire_api_types_sovereign_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_spire_api_types_sovereign_proto_goTypes = []interface{}{
	(AttestedClaims_HostIntegrity)(0), // 0: spire.api.types.AttestedClaims.HostIntegrity
	(*SovereignAttestation)(nil),      // 1: spire.api.types.SovereignAttestation
	(*AttestedClaims)(nil),            // 2: spire.api.types.AttestedClaims
	(*AttestedClaims_GpuMetrics)(nil), // 3: spire.api.types.AttestedClaims.GpuMetrics
}
var file_proto_spire_api_types_sovereign_proto_depIdxs = []int32{
	0, // 0: spire.api.types.AttestedClaims.host_integrity_status:type_name -> spire.api.types.AttestedClaims.HostIntegrity
	3, // 1: spire.api.types.AttestedClaims.gpu_metrics_health:type_name -> spire.api.types.AttestedClaims.GpuMetrics
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_spire_api_types_sovereign_proto_init() }
func file_proto_spire_api_types_sovereign_proto_init() {
	if File_proto_spire_api_types_sovereign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spire_api_types_sovereign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SovereignAttestation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spire_api_types_sovereign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttestedClaims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spire_api_types_sovereign_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttestedClaims_GpuMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spire_api_types_sovereign_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_spire_api_types_sovereign_proto_goTypes,
		DependencyIndexes: file_proto_spire_api_types_sovereign_proto_depIdxs,
		EnumInfos:         file_proto_spire_api_types_sovereign_proto_enumTypes,
		MessageInfos:      file_proto_spire_api_types_sovereign_proto_msgTypes,
	}.Build()
	File_proto_spire_api_types_sovereign_proto = out.File
	file_proto_spire_api_types_sovereign_proto_rawDesc = nil
	file_proto_spire_api_types_sovereign_proto_goTypes = nil
	file_proto_spire_api_types_sovereign_proto_depIdxs = nil
}
