# Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
# SPIRE CSI Driver configuration for external SPIRE Agent

apiVersion: v1
kind: Namespace
metadata:
  name: spire-system
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.spiffe.io
  namespace: spire-system
spec:
  attachRequired: false
  podInfoOnMount: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-csi-driver
  namespace: spire-system
spec:
  selector:
    matchLabels:
      app: spire-csi-driver
  template:
    metadata:
      labels:
        app: spire-csi-driver
    spec:
      serviceAccountName: spire-csi-driver
      hostNetwork: true
      containers:
      - name: driver-registrar
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.8.0
        args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.spiffe.io/csi.sock
        securityContext:
          privileged: true
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: spire-agent-socket
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            if [ -S /run/spire/agent-socket/api.sock ]; then
              echo "SPIRE Agent socket found"
              break
            fi
            echo "Waiting for SPIRE Agent socket..."
            sleep 5
          done
          sleep infinity
        volumeMounts:
        - name: agent-socket
          mountPath: /run/spire/agent-socket
          readOnly: true
      volumes:
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/csi.spiffe.io
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
      - name: agent-socket
        # Unified-Identity - Phase 1: Mount external agent socket from host
        # For kind, we'll need to mount this via kind cluster configuration
        hostPath:
          path: /tmp/spire-agent/public
          type: DirectoryOrCreate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-csi-driver
  namespace: spire-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-csi-driver
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-csi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-csi-driver
subjects:
- kind: ServiceAccount
  name: spire-csi-driver
  namespace: spire-system

